use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let user_dir = manifest_dir.join("..").join("user");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let content_dir = out_dir.join(".user_content");

    if !user_dir.is_dir() {
        write_empty_manifest(&out_dir);
        return;
    }

    // Re-run build if any user file changes
    println!("cargo:rerun-if-changed={}", user_dir.display());

    // Copy user/ → OUT_DIR/.user_content/, collect relative path + mtime
    let mut files: Vec<(String, u64)> = Vec::new();
    collect_files(&user_dir, &user_dir, &content_dir, &mut files)
        .expect("扫描 user/ 目录失败");

    let build_ts = files.iter().map(|(_, m)| *m).max().unwrap_or(0);
    write_manifest(&out_dir, &files, build_ts);
}

fn collect_files(
    src_base: &Path,
    src_dir: &Path,
    dst_root: &Path,
    files: &mut Vec<(String, u64)>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(src_dir)? {
        let entry = entry?;
        let path = entry.path();
        let rel = path
            .strip_prefix(src_base)?
            .to_string_lossy()
            .replace('\\', "/");

        if path.is_dir() {
            collect_files(src_base, &path, dst_root, files)?;
        } else {
            let mtime = entry
                .metadata()?
                .modified()
                .ok()
                .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
                .map(|d| d.as_secs())
                .unwrap_or(0);

            let dst = dst_root.join(&rel);
            if let Some(parent) = dst.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::copy(&path, &dst)?;

            files.push((rel, mtime));
        }
    }
    Ok(())
}

fn write_empty_manifest(out_dir: &Path) {
    let dest = out_dir.join("user_manifest.rs");
    let mut f = fs::File::create(&dest).expect("无法创建 user_manifest.rs");
    writeln!(f, "// AUTO-GENERATED by build.rs").ok();
    writeln!(f, "pub const BUILD_TIMESTAMP: u64 = 0;").ok();
    writeln!(f).ok();
    writeln!(
        f,
        "pub struct EmbeddedFile {{ pub relative_path: &'static str, pub data: &'static [u8], pub mtime: u64 }}"
    )
    .ok();
    writeln!(f).ok();
    writeln!(f, "pub const FILES: &[EmbeddedFile] = &[];").ok();
}

fn write_manifest(out_dir: &Path, files: &[(String, u64)], build_ts: u64) {
    let dest = out_dir.join("user_manifest.rs");
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent).ok();
    }
    let mut f = fs::File::create(&dest).expect("无法创建 user_manifest.rs");

    let out_str = out_dir.to_string_lossy().replace('\\', "/");

    writeln!(f, "// AUTO-GENERATED by build.rs — edit user/ instead").ok();
    writeln!(f, "pub const BUILD_TIMESTAMP: u64 = {};", build_ts).ok();
    writeln!(f).ok();
    writeln!(f, "pub struct EmbeddedFile {{").ok();
    writeln!(f, "    pub relative_path: &'static str,").ok();
    writeln!(f, "    pub data: &'static [u8],").ok();
    writeln!(f, "    pub mtime: u64,").ok();
    writeln!(f, "}}").ok();
    writeln!(f).ok();
    writeln!(f, "pub const FILES: &[EmbeddedFile] = &[").ok();

    for (rel, mtime) in files {
        let data_path = format!("{}/.user_content/{}", out_str, rel);
        writeln!(f, "    EmbeddedFile {{").ok();
        writeln!(f, "        relative_path: \"{}\",", rel).ok();
        writeln!(f, "        data: include_bytes!(\"{}\"),", data_path).ok();
        writeln!(f, "        mtime: {},", mtime).ok();
        writeln!(f, "    }},").ok();
    }

    writeln!(f, "];").ok();
}
